#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_90780_rekrutkrut_real")]
	public partial class dbLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public dbLinqDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.rekrutmenAU_DikaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Info_Save")]
		public int usp_M_Info_Save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pangkat", DbType="VarChar(20)")] string pangkat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pengumuman", DbType="Text")] string pengumuman, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Persyaratan", DbType="Text")] string persyaratan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lokasi", DbType="Text")] string lokasi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Jadwal", DbType="Text")] string jadwal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MateriSeleksi", DbType="Text")] string materiSeleksi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TampilkanDaftar", DbType="Bit")] System.Nullable<bool> tampilkanDaftar, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Auto", DbType="Bit")] System.Nullable<bool> auto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunPendaftaran", DbType="VarChar(4)")] string tahunPendaftaran, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GelombangID", DbType="Int")] System.Nullable<int> gelombangID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pangkat, pengumuman, persyaratan, lokasi, jadwal, materiSeleksi, tampilkanDaftar, auto, tahunPendaftaran, gelombangID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Info_UpdatePanduan")]
		public int usp_M_Info_UpdatePanduan([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pangkat", DbType="VarChar(3)")] string pangkat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Panduan", DbType="VarChar(20)")] string panduan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pangkat, panduan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Pendaftar_INSERT")]
		public int usp_M_Pendaftar_INSERT(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoAnimo", DbType="VarChar(20)")] ref string noAnimo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gelombang", DbType="Int")] System.Nullable<int> gelombang, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunPendaftaran", DbType="VarChar(4)")] string tahunPendaftaran, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nama", DbType="VarChar(50)")] string nama, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pendidikan", DbType="Int")] System.Nullable<int> pendidikan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaSMA", DbType="VarChar(50)")] string namaSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KotaAsalSMA", DbType="VarChar(50)")] string kotaAsalSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropinsiSMA", DbType="VarChar(50)")] string propinsiSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunLulusSMA", DbType="VarChar(4)")] string tahunLulusSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TanggalLahir", DbType="Date")] System.Nullable<System.DateTime> tanggalLahir, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TempatLahir", DbType="VarChar(50)")] string tempatLahir, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoKTP", DbType="VarChar(20)")] string noKTP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Wilayah", DbType="VarChar(3)")] string wilayah, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pangkat", DbType="VarChar(20)")] string pangkat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JenisKelamin", DbType="Int")] System.Nullable<int> jenisKelamin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noAnimo, gelombang, tahunPendaftaran, email, nama, pendidikan, namaSMA, kotaAsalSMA, propinsiSMA, tahunLulusSMA, tanggalLahir, tempatLahir, noKTP, wilayah, pangkat, jenisKelamin);
			noAnimo = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Pendaftar_AddPeserta")]
		public int usp_M_Pendaftar_AddPeserta([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoAnimo", DbType="VarChar(20)")] string noAnimo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(30)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noAnimo, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Info_Pesan_Delete")]
		public int usp_M_Info_Pesan_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InfoId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> infoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToPanda", DbType="VarChar(3)")] string toPanda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), infoId, toPanda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Info_Pesan_UpdateRead")]
		public int usp_M_Info_Pesan_UpdateRead([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InfoId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> infoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToPanda", DbType="VarChar(3)")] string toPanda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), infoId, toPanda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Info_Pesan_Insert")]
		public int usp_M_Info_Pesan_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InfoId", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> infoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Judul", DbType="VarChar(50)")] string judul, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Isi", DbType="VarChar(MAX)")] string isi, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(30)")] string createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), infoId, judul, isi, createdBy);
			infoId = ((System.Nullable<System.Guid>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Info_Pesan_Panda_Insert")]
		public int usp_M_Info_Pesan_Panda_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InfoId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> infoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromPanda", DbType="VarChar(3)")] string fromPanda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToPanda", DbType="VarChar(3)")] string toPanda)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), infoId, fromPanda, toPanda);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Pendaftar_Profile_Insert")]
		public int usp_Pendaftar_Profile_Insert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserEmail", DbType="VarChar(100)")] string userEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pass", DbType="VarChar(50)")] string pass, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nama", DbType="VarChar(50)")] string nama, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TinggiBadan", DbType="Float")] System.Nullable<double> tinggiBadan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeratBadan", DbType="Float")] System.Nullable<double> beratBadan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JenisKelamin", DbType="Int")] System.Nullable<int> jenisKelamin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TempatLahir", DbType="VarChar(50)")] string tempatLahir, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TanggalLahir", DbType="Date")] System.Nullable<System.DateTime> tanggalLahir, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Agama", DbType="Int")] System.Nullable<int> agama, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suku", DbType="VarChar(20)")] string suku, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alamat", DbType="VarChar(MAX)")] string alamat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Kabupaten", DbType="VarChar(50)")] string kabupaten, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Propinsi", DbType="VarChar(50)")] string propinsi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telp", DbType="VarChar(20)")] string telp, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoKTP", DbType="VarChar(20)")] string noKTP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusSD", DbType="VarChar(20)")] string statusSD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaSD", DbType="VarChar(50)")] string namaSD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KotaAsalSD", DbType="VarChar(50)")] string kotaAsalSD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropinsiSD", DbType="VarChar(50)")] string propinsiSD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunLulusSD", DbType="VarChar(4)")] string tahunLulusSD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NEMSD", DbType="Float")] System.Nullable<double> nEMSD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusSMP", DbType="VarChar(20)")] string statusSMP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaSMP", DbType="VarChar(50)")] string namaSMP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KotaAsalSMP", DbType="VarChar(50)")] string kotaAsalSMP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropinsiSMP", DbType="VarChar(50)")] string propinsiSMP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunLulusSMP", DbType="VarChar(4)")] string tahunLulusSMP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NEMSMP", DbType="Float")] System.Nullable<double> nEMSMP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusSMA", DbType="VarChar(20)")] string statusSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaSMA", DbType="VarChar(50)")] string namaSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KotaAsalSMA", DbType="VarChar(50)")] string kotaAsalSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropinsiSMA", DbType="VarChar(50)")] string propinsiSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunLulusSMA", DbType="VarChar(4)")] string tahunLulusSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NEMSMA", DbType="Float")] System.Nullable<double> nEMSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NilaiUN", DbType="Float")] System.Nullable<double> nilaiUN, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pendidikan", DbType="Int")] System.Nullable<int> pendidikan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Jurusan", DbType="VarChar(50)")] string jurusan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaBpk", DbType="VarChar(50)")] string namaBpk, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlamatBpk", DbType="VarChar(MAX)")] string alamatBpk, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PekerjaanBpk", DbType="VarChar(50)")] string pekerjaanBpk, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JabatanBpk", DbType="VarChar(50)")] string jabatanBpk, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaKantorBpk", DbType="VarChar(50)")] string namaKantorBpk, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaIbu", DbType="VarChar(50)")] string namaIbu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlamatIbu", DbType="VarChar(MAX)")] string alamatIbu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PekerjaanIbu", DbType="VarChar(50)")] string pekerjaanIbu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JabatanIbu", DbType="VarChar(50)")] string jabatanIbu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaKantorIbu", DbType="VarChar(50)")] string namaKantorIbu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaWali", DbType="VarChar(50)")] string namaWali, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlamatWali", DbType="VarChar(MAX)")] string alamatWali, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PekerjaanWali", DbType="VarChar(50)")] string pekerjaanWali, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JabatanWali", DbType="VarChar(50)")] string jabatanWali, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaKantorWali", DbType="VarChar(50)")] string namaKantorWali, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PendaftaranKe", DbType="Int")] System.Nullable<int> pendaftaranKe, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PendaftaranDari", DbType="Int")] System.Nullable<int> pendaftaranDari, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prestasi1", DbType="VarChar(30)")] string prestasi1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JuaraKe1", DbType="Int")] System.Nullable<int> juaraKe1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tingkatan1", DbType="Int")] System.Nullable<int> tingkatan1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prestasi2", DbType="VarChar(30)")] string prestasi2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JuaraKe2", DbType="Int")] System.Nullable<int> juaraKe2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tingkatan2", DbType="Int")] System.Nullable<int> tingkatan2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prestasi3", DbType="VarChar(30)")] string prestasi3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JuaraKe3", DbType="Int")] System.Nullable<int> juaraKe3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tingkatan3", DbType="Int")] System.Nullable<int> tingkatan3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(30)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userEmail, pass, nama, tinggiBadan, beratBadan, jenisKelamin, tempatLahir, tanggalLahir, agama, suku, alamat, kabupaten, propinsi, telp, noKTP, statusSD, namaSD, kotaAsalSD, propinsiSD, tahunLulusSD, nEMSD, statusSMP, namaSMP, kotaAsalSMP, propinsiSMP, tahunLulusSMP, nEMSMP, statusSMA, namaSMA, kotaAsalSMA, propinsiSMA, tahunLulusSMA, nEMSMA, nilaiUN, pendidikan, jurusan, namaBpk, alamatBpk, pekerjaanBpk, jabatanBpk, namaKantorBpk, namaIbu, alamatIbu, pekerjaanIbu, jabatanIbu, namaKantorIbu, namaWali, alamatWali, pekerjaanWali, jabatanWali, namaKantorWali, pendaftaranKe, pendaftaranDari, prestasi1, juaraKe1, tingkatan1, prestasi2, juaraKe2, tingkatan2, prestasi3, juaraKe3, tingkatan3, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Panda_Save")]
		public int usp_M_Panda_Save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WilayahId", DbType="VarChar(3)")] string wilayahId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="WilayahName", DbType="VarChar(50)")] string wilayahName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isTaruna, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isBintara, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> isTamtama, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(30)")] string createdBy, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsLakiTaruna", DbType="Bit")] System.Nullable<bool> isLakiTaruna, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPerempuanTaruna", DbType="Bit")] System.Nullable<bool> isPerempuanTaruna, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsLakiBintara", DbType="Bit")] System.Nullable<bool> isLakiBintara, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPerempuanBintara", DbType="Bit")] System.Nullable<bool> isPerempuanBintara, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsLakiTamtama", DbType="Bit")] System.Nullable<bool> isLakiTamtama, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPerempuanTamtama", DbType="Bit")] System.Nullable<bool> isPerempuanTamtama, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Kotama", DbType="VarChar(30)")] string kotama)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), wilayahId, wilayahName, isTaruna, isBintara, isTamtama, createdBy, isActive, isLakiTaruna, isPerempuanTaruna, isLakiBintara, isPerempuanBintara, isLakiTamtama, isPerempuanTamtama, kotama);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Pendaftar_AddPesertaRev")]
		public int usp_M_Pendaftar_AddPesertaRev([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoAnimo", DbType="VarChar(30)")] string noAnimo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(30)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noAnimo, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Users_Save")]
		public int usp_M_Users_Save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="VarChar(30)")] string userId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserRole", DbType="VarChar(10)")] string userRole, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PandaId", DbType="VarChar(5)")] string pandaId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(30)")] string createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userId, userName, password, userRole, pandaId, isActive, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Gelombang_Save")]
		public int usp_M_Gelombang_Save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GelombangID", DbType="Int")] System.Nullable<int> gelombangID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GelombangKe", DbType="Int")] System.Nullable<int> gelombangKe, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunPendaftaran", DbType="VarChar(4)")] string tahunPendaftaran, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangeFrom", DbType="Date")] System.Nullable<System.DateTime> rangeFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangeTo", DbType="Date")] System.Nullable<System.DateTime> rangeTo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BornFrom", DbType="Date")] System.Nullable<System.DateTime> bornFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BornTo", DbType="Date")] System.Nullable<System.DateTime> bornTo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pangkat", DbType="VarChar(20)")] string pangkat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="VarChar(50)")] string createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gelombangID, gelombangKe, tahunPendaftaran, rangeFrom, rangeTo, bornFrom, bornTo, pangkat, isActive, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Info_Pesan_File_Insert")]
		public int usp_M_Info_Pesan_File_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InfoId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> infoId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CaptionName", DbType="VarChar(MAX)")] string captionName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filepath", DbType="VarChar(MAX)")] string filepath)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), infoId, captionName, filepath);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Setting_Save")]
		public int usp_M_Setting_Save([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Laki", DbType="VarChar(MAX)")] string laki, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Perempuan", DbType="VarChar(MAX)")] string perempuan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), laki, perempuan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_M_Pendaftar_INSERTRev")]
		public int usp_M_Pendaftar_INSERTRev(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoAnimo", DbType="VarChar(30)")] ref string noAnimo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gelombang", DbType="Int")] System.Nullable<int> gelombang, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunPendaftaran", DbType="VarChar(4)")] string tahunPendaftaran, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nama", DbType="VarChar(50)")] string nama, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pendidikan", DbType="Int")] System.Nullable<int> pendidikan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NamaSMA", DbType="VarChar(50)")] string namaSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KotaAsalSMA", DbType="VarChar(50)")] string kotaAsalSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropinsiSMA", DbType="VarChar(50)")] string propinsiSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TahunLulusSMA", DbType="VarChar(4)")] string tahunLulusSMA, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TanggalLahir", DbType="Date")] System.Nullable<System.DateTime> tanggalLahir, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TempatLahir", DbType="VarChar(50)")] string tempatLahir, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoKTP", DbType="VarChar(20)")] string noKTP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Wilayah", DbType="VarChar(3)")] string wilayah, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pangkat", DbType="VarChar(20)")] string pangkat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="JenisKelamin", DbType="Int")] System.Nullable<int> jenisKelamin, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Alamat", DbType="VarChar(MAX)")] string alamat, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Kabupaten", DbType="VarChar(50)")] string kabupaten, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Propinsi", DbType="VarChar(50)")] string propinsi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telp", DbType="VarChar(20)")] string telp, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Agama", DbType="Int")] System.Nullable<int> agama, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Suku", DbType="VarChar(20)")] string suku, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TinggiBadan", DbType="Float")] System.Nullable<double> tinggiBadan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BeratBadan", DbType="Float")] System.Nullable<double> beratBadan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noAnimo, gelombang, tahunPendaftaran, email, nama, pendidikan, namaSMA, kotaAsalSMA, propinsiSMA, tahunLulusSMA, tanggalLahir, tempatLahir, noKTP, wilayah, pangkat, jenisKelamin, alamat, kabupaten, propinsi, telp, agama, suku, tinggiBadan, beratBadan);
			noAnimo = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Insert_Nilai")]
		public int usp_Insert_Nilai([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoPeserta", DbType="VarChar(30)")] string noPeserta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasilAngka", DbType="Float")] System.Nullable<double> hasilAngka, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasilHuruf", DbType="VarChar(3)")] string hasilHuruf, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasilLulus", DbType="VarChar(5)")] string hasilLulus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keterangan", DbType="VarChar(MAX)")] string keterangan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipeNilai", DbType="VarChar(20)")] string tipeNilai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noPeserta, hasilAngka, hasilHuruf, hasilLulus, keterangan, tipeNilai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_Insert_NilaiByPesertaPusat")]
		public int usp_Insert_NilaiByPesertaPusat([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoPesertaPusat", DbType="VarChar(30)")] string noPesertaPusat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasilAngka", DbType="Float")] System.Nullable<double> hasilAngka, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasilHuruf", DbType="VarChar(3)")] string hasilHuruf, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HasilLulus", DbType="VarChar(5)")] string hasilLulus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Keterangan", DbType="VarChar(MAX)")] string keterangan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipeNilai", DbType="VarChar(20)")] string tipeNilai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noPesertaPusat, hasilAngka, hasilHuruf, hasilLulus, keterangan, tipeNilai);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
